### ISSUE TITLE
executables.zip not working!

### ISSUE THREAD

**Issue by Coder2354** [ChristopherGLewis/ddo-lite-tools#14]
Whenever I try to unzip executables.zip, windows reports it as invalid.

Error: "Windows cannot open the folder.
The Compressed (zipped) Folder 'C:\Users\(Username)\Downloads\ddo-lite-tools-master\executables.zip' is invalid."

Any help?

Update: Using 7zip I unzipped the file but there is only CannithCrafting.exe and it does not work.

**Comment by Coder2354** [comment]
Update: Using 7zip I unzipped the file but there is only CannithCrafting.exe and it does not work.

**Comment by ChristopherGLewis** [comment]
I'm assuming its a bad download.  Try downloading again using the direct link.

**Comment by Coder2354** [comment]
Link worked, thanks
