### ISSUE TITLE
Issues with Enhancement Requirements in some trees

### ISSUE THREAD

**Issue by Yhelm** [ChristopherGLewis/ddo-lite-tools#15]
So far just seeing this in the Dwarf and Feydark Illusionist trees. I will report again if I find any others. 

Requirements do not seem to be flagging correctly. For example, taking Dwarven Weapon Training (Axe Training) on Tier 1 should unlock the ability to take it on Tier 2 (assuming you have spent enough points in the tree). That is not happing. I verified the Enhancement text file has the correct information for the requirements. However, in the builder the "Requires all of:" is just showing as blank (so I am guessing the system doesn't know how to resolve it).

Same thing is happening in FI with Familiar's Flourish II. Can't take it even though it should be able to.

**Comment by ChristopherGLewis** [comment]
Potential fix in flight

**Comment by ChristopherGLewis** [comment]
This should be fixed in 4.0.2.  Please review.

**Comment by Yhelm** [comment]
Confirmed it is now working as intended. Thanks!
