### ISSUE TITLE
Issues with selecting enhancements with divine disciple

### ISSUE THREAD

**Issue by LarsIndreeide** [ChristopherGLewis/ddo-lite-tools#17]
The abilities "Spell knowledge" 1 2 & 3 doesn't get any selectors when selected. Same with "Prophetic Zenith".

**Comment by ChristopherGLewis** [comment]
Looks like SharedSelector is borked.  Reviewing

**Comment by ChristopherGLewis** [comment]
This should be fixed in 4.0.2.  Please review.

**Comment by LarsIndreeide** [comment]
Works perfectly now.
