### ISSUE TITLE
Entered Destiny pdp not saving

### ISSUE THREAD

**Issue by Yhelm** [ChristopherGLewis/ddo-lite-tools#18]
When closing the build and reopening (after saving) the saved build has all of its perm destiny points reset to 0. Upon entering the Destiny editor, the points are then defaulted to the minimum starting number (12).

**Comment by ChristopherGLewis** [comment]
This only occurs if there are no destiny points spent.

If you spend any destiny points, the PDP line is added to save file.

I might fix this if its trival.

**Comment by ChristopherGLewis** [comment]
Fixed in next release
