### ISSUE TITLE
Horizon Walker, Favored Enemy: Evil Outsider Enhancement error 

### ISSUE THREAD

**Issue by Yhelm** [ChristopherGLewis/ddo-lite-tools#19]
When selecting Favored Enemy: Evil Outsider from the Horizon Walker tree, it is giving an Antireq error for having ANY Favored Enemy feat, not just Evil Outsider.

Error message in builder is "Error: Antireq for Feat: Favored Enemy". Confirmed that only Favored Enemy feats taken in the 6 levels of Ranger I had were Fey and Giant.

**Comment by ChristopherGLewis** [comment]
This is generic for all Favored Enemy enhancements right now.  Working on a fix.

**Comment by ChristopherGLewis** [comment]
Fixed in next release
