### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by iplaywithdrums** [ChristopherGLewis/ddo-lite-tools#24]
Hello! Just reporting a few minor bugs:

- alchemist feat liquid courage should be insightful courage
- feydark enhancement enhanced invisibility should be reality bulwark
- bombardier enhancement efficient metamagic should be 2AP/rank instead of 1AP (missing Cost: 2)
- bombardier enhancement SLA smoke bomb should have 3 ranks (missing Ranks: 3)
- bombardier enhancement elemental obliteration should have 3 ranks (missing Ranks: 3)

**Comment by rosenzzzz** [comment]
Casual completion favor is calculated incorrectly. Fractions should be rounded up (i.e. 9 base favor should get 5 on casual not 4).

**Comment by ChristopherGLewis** [comment]
Haven't looked at the theme issue - I'd try it with the standard theme.  Enhancements s/b fixed
