### ISSUE TITLE
New Forums

### ISSUE THREAD

**Issue by Yhelm** [ChristopherGLewis/ddo-lite-tools#30]
Wasn't sure where else to leave this so you would see it. Once you have the info we can delete this or whatever is needed. 

I have made a post for this project in the Creators section of the new forums. You will find it here:

[https://forums.ddo.com/index.php?threads/ddo-character-builder-lite.138/](https://forums.ddo.com/index.php?threads/ddo-character-builder-lite.138/)

Just didn't want to lose the momentum we have on this at the moment. I will be posting any additional issues I find here for you.

**Comment by ChristopherGLewis** [comment]
I've added a forum post here: [OFFICAL: Character Builder Lite](https://forums.ddo.com/index.php?threads/offical-character-builder-lite.97/) so I can update the current release info on the main page.

**Comment by Yhelm** [comment]
Perfect. I will point mine to yours and remove the info. Thanks!Jason Schmick(via iPhone)On May 7, 2023, at 1:32 PM, Christopher Lewis ***@***.***> wrote:﻿
I've added a forum post here: OFFICAL: Character Builder Lite so I can update the current release info on the main page.
