### ISSUE TITLE
Missing lvl 31 and 32 items

### ISSUE THREAD

**Issue by Yhelm** [ChristopherGLewis/ddo-lite-tools#31]
Currently missing a couple of things...

- Missing one Ability Increase at lvl 32 (builder only goes up to 28)
- Missing the Destiny Points you get at levels 31 and 32 (should be +4 DP at each level for a total of +8 at lvl 32).

Updates to Classes, Enhancement and Spells can be found here:

https://forums-old.ddo.com/forums/showthread.php/455712-Character-Builder-Lite/page60

**Comment by ChristopherGLewis** [comment]
I have a working fix for this - working through the testing iterrations
