### ISSUE TITLE
Dark Hunter can not enter skill points for open lock or disable device

### ISSUE THREAD

**Issue by BlameTroi** [ChristopherGLewis/ddo-lite-tools#32]
This is in the 4.3 release. The UI shows the skills as available for full spend (light grey background) but will not accept any points at any level. Other skills spend as expected.

**Comment by ChristopherGLewis** [comment]
working through this right now  - lots of hard coded places checking for Rog/Art.  Adding a new field to the class.txt for Trapper

**Comment by BlameTroi** [comment]
Cool thanks!
