### ISSUE TITLE
subscript out of range error selecting blightcaster t2 thorn or bile

### ISSUE THREAD

**Issue by BlameTroi** [ChristopherGLewis/ddo-lite-tools#33]
Hi. I was working through a blightcaster build and got a crash in enhancements. The error was subscript out of range. I've attached the backup.bld file. I was entering blightcaster enhancements and had selected the splinterbolt option for thorn or bile.
[Backup.zip](https://github.com/ChristopherGLewis/ddo-lite-tools/files/12539140/Backup.zip)

**Comment by ChristopherGLewis** [comment]
Appears to be fixed.  Let me know if  you have any issues after today's release
