### ISSUE TITLE
Compendium: wrong favor

### ISSUE THREAD

**Issue by MIvanIsten** [ChristopherGLewis/ddo-lite-tools#36]
The Devils to Pay is only 5 favor, not 6.
What Dreams May Come is only 5 favor, not 6.
Fire Over Morgrave is missing

QuestName: Fire Over Morgrave
Pack: Vecna Unleashed
Patron: Morgrave University
Favor: 9
Level: 34
Epic: 34
Style: Raid

**Comment by ChristopherGLewis** [comment]
Fixed with 2024.03.17 release
