### ISSUE TITLE
Issue with taking IC on a Multiclass Dragon Lord

### ISSUE THREAD

**Issue by Dielzen** [ChristopherGLewis/ddo-lite-tools#40]
https://cdn.discordapp.com/attachments/1237859779431628900/1241242836561559552/image.png?ex=66497cf9&is=66482b79&hm=091e6d9b91b76f36334b3123d71ea9c287167b7ec23e73b1fe3f41ad94de49c2&

The program is saying this feat selection is invalid, but it works in game (verified by actual play)

**Comment by ChristopherGLewis** [comment]
I can't see that discord link.

**Comment by ChristopherGLewis** [comment]
Fixed in U68 release
