### ISSUE TITLE
2020-11-12 download detected as infected with malware

### ISSUE THREAD

**Issue by wilcoxon** [ChristopherGLewis/ddo-lite-tools#5]
Specifically, it comes up as infected with Gen:Variant.Johnnie.263751.  Is this a false positive or did the download get infected?

It appears to be browser hijack malware.  Does the installer change anything with home page, search engine, or anything else in the browser?

**Comment by ChristopherGLewis** [comment]
This is a false positive.

There's nothing in the application that changes browser settings.
