### ISSUE TITLE
'X'ing out of the compendium causes an error to show up.

### ISSUE THREAD

**Issue by LouDaCrisp** [ChristopherGLewis/ddo-lite-tools#9]
'X'ing out of the compendium causes an error to show up. Image below.

![image](https://user-images.githubusercontent.com/22990863/105428655-d1499700-5c1d-11eb-9df7-9fcb7436c591.png)

**Comment by ChristopherGLewis** [comment]
I can't reproduce - can you tell me if this compendium had been saved yet?

**Comment by LouDaCrisp** [comment]
Looks like after latest update, this issue doesn't show up.
